### ISSUE TITLE
Infinite recursion when serializing bounds

### ISSUE THREAD

**Issue by abyrd** [conveyal/gtfs-validator#17]
```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Infinite recursion (StackOverflowError) (through reference chain: java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->java.awt.geom.Double["bounds2D"]->...

at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:658)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
    at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:541)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:644)
    at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
...
Caused by: java.lang.StackOverflowError
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:455)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:367)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:660)
    ... 1011 more

```

**Comment by abyrd** [comment]
It looks like this is caused by java.awt.geom.Rectangle2D.Double#getBounds2D, which recursively returns a new Rectangle2D. I'm still searching for the object being serialized that contains this.

**Comment by abyrd** [comment]
I have just put a `@JsonIgnore` annotation on `public Rectangle2D bounds;` in com.conveyal.gtfs.validator.json.FeedValidationResult as a workaround.

**Comment by mattwigway** [comment]
We need to add a mixin annotation to the objectmapper to ignore Bounds::getBounds2D

**Comment by barbeau** [comment]
@abyrd and @mattwigway It looks like the workaround that @abyrd mentioned in https://github.com/conveyal/gtfs-validator/issues/17#issuecomment-114882335 for this issue doesn't exist in the master branch in com.conveyal.gtfs.validator.json.FeedValidationResult#bounds.  Any objections to us opening a PR with this workaround so we can make it accessible to others?

This issue is blocking us from seeing the GTFS validation results in our gtfs-realtime-validator (https://github.com/CUTR-at-USF/gtfs-realtime-validator/pull/30).

cc @mohangandhiGH

**Comment by abyrd** [comment]
Hi @barbeau. I listed the above workaround as part of my investigation into what caused the problem, but I almost never use this GTFS validator library so I don't know what the side effects of making these changes might be for other people's projects (within Conveyal or outside). @mattwigway do you think just not serializing that bounds field is going to cause a problem, or do we need to serialize it but selectively block the recursion?

**Comment by barbeau** [comment]
@abyrd and @mattwigway I opened a PR for the workaround here (not serializing the bounds):
https://github.com/conveyal/gtfs-validator/pull/39

As far as I can tell, the output of the validator isn't currently usable because of the StackOverflow issue, so the PR at least makes it functional.  And, from browsing the validation UI, I don't think the bounds are surfaced there either.
